[bar]
order = ["main"]

[bar.main]
position = "top"
thickness = 40
shadow = false
panel_overlap = 0
radius = 0
margin_ends = 0
margin_edge = 0
padding = 20
widget_spacing = 10
scale = 1.1

start  = ["launcher", "wallpaper", "workspaces"]
center = ["clock"]
end    = ["media", "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "control-center", "session"]

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 10

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1317.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[shell.panel]
launcher_categories = false

[theme]
source = "wallpaper"

[wallpaper]
directory = "/home/skykanin/Pictures/wallpapers"

    [wallpaper.default]
    path = "/home/skykanin/Pictures/wallpapers/planets.jpg"

    [wallpaper.last]
    path = "/home/skykanin/Pictures/wallpapers/planets.jpg"
